package com.droiddevgeeks.crashsink;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import android.content.Context;

import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Compile-time and runtime proof that crashsink's (Kotlin) <b>public API</b> is fully usable from
 * Java. This single Java class is the library's permanent, CI-enforced interop guard.
 *
 * The whole public surface is exercised here: the SAM {@link CrashSink}, the single static
 * {@code create(...)} factory (both the defaults form and the explicit form generated by
 * {@code @JvmOverloads}), the {@code DEFAULT_*} constants, and the
 * {@code install}/{@code startCapturing}/{@code stopCapturing}/{@code shutdown} lifecycle. The
 * implementation classes are {@code internal} (not Java-facing) and are covered by Kotlin tests.
 */
public class JavaInteropTest {

    @Rule public TemporaryFolder tmp = new TemporaryFolder();

    private Thread.UncaughtExceptionHandler original;

    @Before public void setUp() {
        original = Thread.getDefaultUncaughtExceptionHandler();
    }

    @After public void tearDown() {
        Thread.setDefaultUncaughtExceptionHandler(original);
    }

    /** A Context whose filesDir points at a temp folder; packageManager left null (metadata defaults). */
    private Context contextWithFilesDir() throws Exception {
        Context ctx = mock(Context.class);
        when(ctx.getFilesDir()).thenReturn(tmp.newFolder("files"));
        return ctx;
    }

    @Test public void crashSinkImplementableAsJavaLambda() {
        List<String> got = new ArrayList<>();
        CrashSink sink = (token, exceptionValues, level, culprit, timestamp, contexts) -> got.add(culprit);
        sink.submit("tok", "[]", "fatal", "com.example.Foo in bar", 1L, "{}");
        assertEquals(1, got.size());
        assertEquals("com.example.Foo in bar", got.get(0));
    }

    @Test public void defaultConstantsReadableFromJava() {
        assertEquals(20, CrashReporter.DEFAULT_FILE_CAP);
        assertEquals(1000L, CrashReporter.DEFAULT_FLUSH_TIMEOUT_MS);
    }

    @Test public void createWithDefaultsAndLifecycleCallableFromJava() throws Exception {
        CrashSink sink = (token, ev, level, culprit, ts, ctx) -> { /* no-op */ };

        // @JvmOverloads form: fileCap / flushTimeout omitted → defaults applied.
        CrashReporter reporter = CrashReporter.create(contextWithFilesDir(), sink, "com.example.");
        assertNotNull(reporter);
        reporter.startCapturing("session-j");
        reporter.stopCapturing();
        reporter.shutdown();
    }

    @Test public void createWithExplicitTuningCallableFromJava() throws Exception {
        CrashSink sink = (token, ev, level, culprit, ts, ctx) -> { /* no-op */ };

        // Full form: fileCap + flushTimeout passed explicitly.
        CrashReporter reporter = CrashReporter.create(contextWithFilesDir(), sink, "com.example.", 50, 1500L);
        assertNotNull(reporter);
        reporter.startCapturing("session-j-tuned");
        reporter.stopCapturing();
        reporter.shutdown();
    }
}
